# .NET Desktop
# Build and run tests for .NET Desktop or Windows classic desktop solutions.
# Add steps that publish symbols, save build artifacts, and more:
# https://docs.microsoft.com/azure/devops/pipelines/apps/windows/dot-net
name: $(TeamProject)_$(Build.DefinitionName)_$(SourceBranchName)_$(Date:yyyy.MM.dd)$(Rev:.r)

trigger:
- master

pool:
  vmImage: 'windows-latest'

variables:
  solution: '**/ScriptScripter.sln'
  buildPlatform: 'Any CPU'
  buildConfiguration: 'Release'

steps:
- script: echo '$(Build.BuildNumber)'
- task: NuGetToolInstaller@1

- task: NuGetCommand@2
  inputs:
    restoreSolution: '$(solution)'

- task: PowerShell@1
  displayName: 'Apply Version To Assemblies PowerShell Script'
  inputs:
    scriptName: $(build.sourcesdirectory)/BuildUtilities/ApplyVersionToAssemblies.ps1

- task: VSBuild@1
  inputs:
    solution: '$(solution)'
    platform: '$(buildPlatform)'
    configuration: '$(buildConfiguration)'

- task: CopyFiles@2
  displayName: 'Copy DesktopApp Files to Artifacts'
  inputs:
    SourceFolder: '$(build.sourcesdirectory)'
    Contents: |
     **\ScriptScripter.DesktopApp\bin\$(buildConfiguration)\*
     **\ScriptScripter.Processor\smo_libs\v12.0\*
    TargetFolder: '$(Build.ArtifactStagingDirectory)\DesktopApp'
    CleanTargetFolder: true
    OverWrite: true
    flattenFolders: true
- task: CopyFiles@2
  displayName: 'Copy Command Files to Artifacts'
  inputs:
    SourceFolder: '$(build.sourcesdirectory)'
    Contents: |
     **\ScriptScripter.Command\bin\$(buildConfiguration)\*
     **\ScriptScripter.Processor\smo_libs\v12.0\*
    TargetFolder: '$(Build.ArtifactStagingDirectory)\Command'
    CleanTargetFolder: true
    OverWrite: true
    flattenFolders: true

- task: PublishBuildArtifacts@1
  inputs:
    PathtoPublish: '$(Build.ArtifactStagingDirectory)'
    ArtifactName: '$(Build.BuildNumber)'
    publishLocation: 'Container'
